# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rocks', '0003_rock_crystal_habit'),
    ]

    operations = [
        migrations.AddField(
            model_name='rock',
            name='specific_gravity',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
